---
- name: install arma 3
  command: "{{ steamcmd_directory }}steamcmd.sh +login {{ steamcmd_steam.username }} {{ steamcmd_steam.password }} +force_install_dir {{ arma3_install_dir }} +app_update 233780 validate +quit"
  register: output
  become: yes
  become_user: "{{ steamcmd_user }}"

- name: create cryptkeyfile
  template:
    src: secret.key.j2
    dest: "{{ steamcmd_user_home }}secret.key"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0600'

- name: install openssl for password encryption
  package:
    name: openssl lftp
    state: present

- name: encrypt steampass for parameter file
  shell: 'echo {{ steamcmd_steam.password }} | openssl enc -a -e -aes-256-cbc -md md5 -pass pass:{{ cryptkey }} 2>/dev/null'
  register: steampass
  no_log: true

- name: generate ArmA 3 parameter file for the service
  template:
    src: config.cfg.server.j2
    dest: "{{ steamcmd_user_home }}config.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0600'

- name: generate ArmA 3 server.cfg
  template:
    src: server.cfg.j2
    dest: "{{ arma3_install_dir }}server.cfg"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0600'

- name: copy server.sh
  template:
    src: server.sh.j2
    dest: "{{ steamcmd_user_home }}server.sh"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: '0744'

- name: create untifile
  template:
    src: arma3-server.j2
    dest: /etc/systemd/system/arma3-server.service
    owner: root
    group: root
    mode: '0644'

- name: enable Arma 3 service
  systemd:
    name: arma3-server
    enabled: True
    daemon_reload: yes
